"""
he_names.py - Hebrew names for competitions, cities and teams used by this project.

Used by build_fixtures.py (every run) and by backfill_hebrew.py (one-off pass over an
existing fixtures.js). Anything not found in these dictionaries falls back to
transliterate(), a simple rule-based English->Hebrew phonetic converter, so the site
never shows a name outside these dictionaries in Latin script.

To fix a specific name: add/edit an entry here (HE_TEAMS keyed by the exact English
team name as it appears in fixtures.js, HE_CITIES keyed by "City|Country"), then re-run
backfill_hebrew.py (no API calls, instant) or build_fixtures.py.
"""

HE_COMPETITIONS = {
    "Premier League": "הפרמייר ליג",
    "Championship": "הצ'מפיונשיפ",
    "League One": "ליג וואן",
    "League Two": "ליג טו",
    "FA Cup": "גביע ה-FA",
    "EFL Cup": "EFL קאפ",
    "EFL Trophy": "EFL טרופי",
    "La Liga": "לה ליגה",
    "Segunda": "סגונדה דיביזיון",
    "Copa del Rey": "קופה דל ריי",
    "Bundesliga": "בונדסליגה",
    "2. Bundesliga": "בונדסליגה 2",
    "DFB-Pokal": "גביע גרמניה",
    "Ligue 1": "ליג 1 הצרפתית",
    "Ligue 2": "ליג 2 הצרפתית",
    "Coupe de France": "גביע צרפת",
    "Eredivisie": "הארדיביזי",
    "KNVB Beker": "גביע הולנד",
    "Serie A": "סרייה A",
    "Serie B": "סרייה B",
    "Coppa Italia": "קופה איטליה",
    "Ekstraklasa": "אקסטרהקלאסה",
    "Puchar Polski": "גביע פולין",
    "Champions League": "ליגת האלופות",
    "Europa League": "הליגה האירופית",
    "Conference League": "ליגת הקונפרנס",
}

HE_TEAMS = {
    "1. FC Heidenheim": "היידנהיים",
    "1. FC Kaiserslautern": "קייזרסלאוטרן",
    "1. FC Köln": "קלן",
    "1. FC Magdeburg": "מגדבורג",
    "1. FC Nürnberg": "נירנברג",
    "1899 Hoffenheim": "הופנהיים",
    "AC Milan": "מילאן",
    "Accrington ST": "אקרינגטון סטנלי",
    "Achilles Veen": "אכילס פין",
    "ACV": "ACV",
    "AD Ceuta FC": "סאוטה",
    "ADO Den Haag": "ADO דן האג",
    "AFC '34": "AFC '34",
    "AFC Amsterdam": "AFC אמסטרדם",
    "AFC Telford United": "טלפורד יונייטד",
    "AFC Wimbledon": "AFC ווימבלדון",
    "Ajax": "אייאקס",
    "Alaves": "אלאבס",
    "Albacete": "אלבסטה",
    "Alcazar": "ספורטינג דה אלקסר",
    "Almeria": "אלמריה",
    "Anaitasuna": "קלוב דפורטיבו אנאיטסונה",
    "Angers": "אנז'ה",
    "Annecy": "אנסי",
    "Arezzo": "ארצו",
    "Arka Gdynia": "ארקה גדיניה",
    "Arminia Bielefeld": "ארמיניה בילפלד",
    "Arsenal": "ארסנל",
    "Arsenal U21": "ארסנל U21",
    "AS Roma": "רומא",
    "Ascoli": "אסקולי",
    "Aston Villa": "אסטון וילה",
    "Aston Villa U21": "אסטון וילה U21",
    "Atalanta": "אטלנטה",
    "Athletic Club": "אתלטיק בילבאו",
    "Atletico Calatayud": "אתלטיקו קלטיוד",
    "Atletico Madrid": "אתלטיקו מדריד",
    "Atlético Melilla": "אתלטיקו מלייה",
    "Auriense": "אווריינסה",
    "Auxerre": "אוסר",
    "Avellino": "אוולינו",
    "Avia Świdnik": "אביה שווידניק",
    "AZ Alkmaar": "AZ אלקמאר",
    "Barcelona": "ברצלונה",
    "Barendrecht": "ברנדרכט",
    "Barnet": "בארנט",
    "Barnsley": "בארנסלי",
    "Bayer Leverkusen": "באייר לברקוזן",
    "Bayern München": "באיירן מינכן",
    "Baztán": "בסטן",
    "Benevento": "בנוונטו",
    "Birmingham": "בירמינגהם",
    "Blackburn": "בלקברן",
    "Blackpool": "בלקפול",
    "Bologna": "בולוניה",
    "Bolton": "בולטון",
    "Borussia Dortmund": "בורוסיה דורטמונד",
    "Borussia Mönchengladbach": "בורוסיה מנשנגלדבך",
    "Boulogne": "בולון",
    "Bournemouth": "בורנמות'",
    "Bradford": "ברדפורד",
    "Braintree": "בריינטרי",
    "Brentford": "ברנטפורד",
    "Brentford U21": "ברנטפורד U21",
    "Brighton": "ברייטון",
    "Brighton U21": "ברייטון U21",
    "Bristol City": "בריסטול סיטי",
    "Bristol Rovers": "בריסטול רוברס",
    "Bromley": "ברומלי",
    "Burgos": "בורגוס",
    "Burnley": "ברנלי",
    "Burton Albion": "ברטון אלביון",
    "Cadiz": "קאדיס",
    "Cagliari": "קליארי",
    "Cambridge United": "קיימברידג' יונייטד",
    "Cambuur": "קמבור",
    "Cardiff": "קארדיף",
    "Carrarese": "קררזה",
    "Castellón": "קסטיון",
    "Catanzaro": "קטנזארו",
    "CD San Jose": "סן חוזה",
    "Celta de Vigo II": "סלטה ויגו II",
    "Celta Vigo": "סלטה ויגו",
    "Cesena": "צ'זנה",
    "Ceuta 6 de Junio": "סאוטה 6 דה חוניו",
    "Charlton": "צ'רלטון",
    "Chelsea": "צ'לסי",
    "Chelsea U21": "צ'לסי U21",
    "Cheltenham": "צ'לטנהאם",
    "Chesterfield": "צ'סטרפילד",
    "Chippenham Town": "צ'יפנהאם טאון",
    "Chrobry Głogów": "חרוברי גלוגוב",
    "Cirencester Town": "סיירנססטר טאון",
    "Clermont Foot": "קלרמון פוט",
    "Colchester": "קולצ'סטר יונייטד",
    "Como": "קומו",
    "Cordoba": "קורדובה",
    "Coventry": "קובנטרי",
    "Cracovia Krakow": "קרקוביה קרקוב",
    "Crawley Town": "קרולי טאון",
    "Cray Wanderers": "קריי וונדררס",
    "Cremonese": "קרמונזה",
    "Crewe": "קרו",
    "Crowborough Athletic": "קראוובורו אתלטיק",
    "Crystal Palace": "קריסטל פאלאס",
    "Crystal Palace U21": "קריסטל פאלאס U21",
    "Dagenham & Redbridge": "דגנהאם אנד רדברידג'",
    "Deportivo La Coruna": "דפורטיבו לה קורוניה",
    "Derby": "דרבי",
    "Dijon": "דיז'ון",
    "Doncaster": "דונקסטר",
    "Dovo": "דובו",
    "Dunkerque": "דנקרק",
    "DVS 33 Ermelo": "DVS 33 ארמלו",
    "Dynamo Dresden": "דינמו דרזדן",
    "Eemdijk": "אמדייק",
    "Eibar": "אייבר",
    "Eintracht Braunschweig": "איינטרכט בראונשווייג",
    "Eintracht Frankfurt": "איינטרכט פרנקפורט",
    "Elche": "אלצ'ה",
    "Eldense": "אלדנסה",
    "Empoli": "אמפולי",
    "Energie Cottbus": "אנרגי קוטבוס",
    "Espanyol": "אספניול",
    "Estac Troyes": "טרואה",
    "Everton": "אברטון",
    "Everton U21": "אברטון U21",
    "EVV": "EVV",
    "Excelsior": "אקסלסיור",
    "Excelsior '31": "אקסלסיור '31",
    "Excelsior Maassluis": "אקסלסיור מאסלואיס",
    "Exeter City": "אקסטר סיטי",
    "Exmouth": "אקסמות' טאון",
    "Farnborough": "פארנבורו",
    "Farnham Town": "פארנהאם טאון",
    "FC Andorra": "FC אנדורה",
    "FC Augsburg": "אוגסבורג",
    "FC Schalke 04": "שאלקה 04",
    "FC St. Pauli": "זנקט פאולי",
    "Feyenoord": "פיינורד",
    "Fiorentina": "פיורנטינה",
    "Fleetwood Town": "פליטווד טאון",
    "Fortuna Sittard": "פורטונה סיטארד",
    "Frisia": "פריזיה",
    "Frosinone": "פרוזינונה",
    "FSV Mainz 05": "מיינץ 05",
    "Fulham": "פולהאם",
    "Fulham U21": "פולהאם U21",
    "Gainsborough Trinity": "גיינסבורו טריניטי",
    "Gemert": "חמרט",
    "Genoa": "ג'נואה",
    "Getafe": "חטאפה",
    "Gillingham": "ג'ילינגהאם",
    "Girona": "ג'ירונה",
    "GKS Katowice": "GKS קטוביצה",
    "GO Ahead Eagles": "גו אהד איגלס",
    "Górnik Łęczna": "גורניק לנצ'נה",
    "Gornik Zabrze": "גורניק זבז'ה",
    "Granada CF": "גרנדה",
    "Grenoble": "גרנובל",
    "Grimsby": "גרימסבי",
    "Groene Ster": "חרונה סטר",
    "Groesbeek": "VV חרמניה",
    "Groningen": "חרונינגן",
    "Güímar": "אתלטיקו אוניון גוימאר",
    "Guingamp": "גאנגאן",
    "GVVV Veenendaal": "GVVV פינדאל",
    "Halsteren": "הלסטרן",
    "Hamburger SV": "המבורגר SV",
    "Hampton & Richmond": "המפטון אנד ריצ'מונד",
    "Hannover 96": "הנובר 96",
    "Heerenveen": "הרנפין",
    "Hellas Verona": "הלאס ורונה",
    "Hemel Hempstead Town": "המל המפסטד טאון",
    "Hertha BSC": "הרטה ברלין",
    "HHC": "HHC",
    "Holstein Kiel": "הולשטיין קיל",
    "Hoogeveen": "הוגפין",
    "Hortaleza": "ספורטינג הורטלזה",
    "Huddersfield": "האדרספילד",
    "Hull City": "האל סיטי",
    "Ijsselmeervogels": "אייסלמירפוגלס",
    "Inter": "אינטר",
    "Ipswich": "איפסוויץ'",
    "Ipswich Town U21": "איפסוויץ' טאון U21",
    "Jagiellonia": "יגלוניה ביאליסטוק",
    "JOS Watergraafsmeer": "JOS ווטרחרפשמיר",
    "Juve Stabia": "יובה סטאביה",
    "Juventus": "יובנטוס",
    "Karlsruher SC": "קרלסרוהה",
    "Kloetinge": "קלוטינחה",
    "Koninklijke HFC": "קוניקלייקה HFC",
    "Korona Kielce": "קורונה קיילצה",
    "Kozakken Boys": "קוזקן בויז",
    "Las Palmas": "לאס פלמאס",
    "Laval": "לאבאל",
    "Lazio": "לאציו",
    "Le Havre": "לה הבר",
    "Le Mans": "לה מאן",
    "Leamington": "לימינגטון",
    "Lebrijana": "לבריחנה",
    "Lecce": "לצ'ה",
    "Lech Poznan": "לך פוזנן",
    "Lechia Gdansk": "לכיה גדנסק",
    "Leeds": "לידס",
    "Leeds United U21": "לידס יונייטד U21",
    "Leganes": "לגאנס",
    "Legia Warszawa": "לגיה ורשה",
    "Leicester": "לסטר",
    "Lens": "לאנס",
    "Levante": "לבאנטה",
    "Leyton Orient": "לייטון אוריינט",
    "Lille": "ליל",
    "Lincoln": "לינקולן",
    "Liverpool": "ליברפול",
    "Liverpool U21": "ליברפול U21",
    "Lorient": "לוריאן",
    "Luton": "לוטון",
    "Lyon": "ליון",
    "Maidstone Utd": "מיידסטון יונייטד",
    "Malaga": "מלאגה",
    "Mallorca": "מיורקה",
    "Manchester City": "מנצ'סטר סיטי",
    "Manchester City U21": "מנצ'סטר סיטי U21",
    "Manchester United": "מנצ'סטר יונייטד",
    "Mansfield Town": "מנספילד טאון",
    "Mantova": "מנטובה",
    "Maracena": "מרסנה",
    "Marseille": "מארסיי",
    "Merthyr Town": "מרתיר טאון",
    "Metz": "מץ",
    "Middlesbrough": "מידלסברו",
    "Millwall": "מילוול",
    "Milton Keynes Dons": "מילטון קיינס דונס",
    "Modena": "מודנה",
    "Monaco": "מונאקו",
    "Montpellier": "מונפלייה",
    "Monza": "מונצה",
    "Motor Lublin": "מוטור לובלין",
    "Nancy": "נאנסי",
    "Nantes": "נאנט",
    "Napoli": "נאפולי",
    "NEC Nijmegen": "NEC ניימכן",
    "Needham Market": "נידהאם מרקט",
    "Newcastle": "ניוקאסל",
    "Newcastle United U21": "ניוקאסל יונייטד U21",
    "Newport County": "ניופורט קאונטי",
    "Nice": "ניס",
    "Nieciecza": "נייצ'יצ'ה",
    "Noja": "נוחה",
    "Noordwijk": "נורדוויק",
    "Northampton": "נורת'המפטון",
    "Norwich": "נוריץ'",
    "Nottingham Forest": "נוטינגהאם פורסט",
    "Nottingham Forest U21": "נוטינגהאם פורסט U21",
    "Notts County": "נוטס קאונטי",
    "Odra Opole": "אודרה אופולה",
    "Oldham": "אולדהאם אתלטיק",
    "Olimpia Grudziądz": "אולימפיה גרודזיונדז",
    "Osasuna": "אוסאסונה",
    "Oviedo": "אוביידו",
    "Oxford United": "אוקספורד יונייטד",
    "Padova": "פדובה",
    "Palermo": "פלרמו",
    "Paris FC": "פריז FC",
    "Paris Saint Germain": "פריז סן ז'רמן",
    "Parma": "פארמה",
    "PAU": "פאו",
    "PEC Zwolle": "PEC זוואלה",
    "Peterborough": "פיטרבורו",
    "Piast Gliwice": "פיאסט גליביצה",
    "Pinatar": "אתלטיקו פינטארנסה",
    "Pisa": "פיזה",
    "Plymouth": "פלימות'",
    "Podhale Nowy Targ": "פודהאלה נובי טארג",
    "Pogoń Siedlce": "פוגון שיאדלצה",
    "Pogon Szczecin": "פוגון שצ'צ'ין",
    "Polonia Bytom": "פולוניה ביטום",
    "Polonia Środa": "פולוניה שרודה",
    "Polonia Warszawa": "פולוניה ורשה",
    "Port Vale": "פורט וייל",
    "Portsmouth": "פורטסמות'",
    "Prat": "פראט",
    "Preston": "פרסטון",
    "PSV Eindhoven": "PSV איינדהובן",
    "Purmersteijn": "פורמרסטיין",
    "Puszcza Niepołomice": "פושצ'ה ניפולומיצה",
    "QPR": "קווינס פארק ריינג'רס",
    "Racing Santander": "רסינג סנטנדר",
    "Radomiak Radom": "רדומיאק רדום",
    "Raków Częstochowa": "ראקוב צ'נסטוחובה",
    "Rayo Vallecano": "ראיו וייקאנו",
    "RB Leipzig": "לייפציג",
    "Reading": "רדינג",
    "Real Betis": "ריאל בטיס",
    "Real Madrid": "ריאל מדריד",
    "Real Sociedad": "ריאל סוסיאדד",
    "Real Sociedad II": "ריאל סוסיאדד II",
    "RED Star FC 93": "רד סטאר 93",
    "Reims": "ראנס",
    "Rennes": "רן",
    "Ribadesella CF": "ריבדסיה",
    "Rijnvogels": "ריינפוגלס",
    "RKAV Volendam": "RKAV פולנדם",
    "Rochdale": "רוצ'דייל",
    "Rodez": "רודז",
    "ROHDA Raalte": "רוהדה ראלטה",
    "Roosendaal": "רוזנדל",
    "Rotherham": "רות'רהאם",
    "Rot-Weiß Essen": "רוט-וייס אסן",
    "Ruch Chorzów": "רוך חוז'וב",
    "Sabadell": "סבאדל",
    "Saint Etienne": "סנט אטיין",
    "Salford City": "סאלפורד סיטי",
    "Sampdoria": "סמפדוריה",
    "San Rafael": "סנט ראפל",
    "Sassuolo": "סאסואולו",
    "SC Freiburg": "פרייבורג",
    "SC Genemuiden": "SC חנמוידן",
    "SC Paderborn 07": "פדרבורן 07",
    "Sevilla": "סביליה",
    "SG Sonnenhof Grossaspach": "זונהוף גרוסאשפאך",
    "Sheffield Utd": "שפילד יונייטד",
    "Sheffield Wednesday": "שפילד וונזדיי",
    "Shrewsbury": "שרוסברי",
    "Siarka Tarnobrzeg": "סיארקה טרנוברז'ג",
    "Slask Wroclaw": "שלונסק ורוצלב",
    "Śląsk Wrocław II": "שלונסק ורוצלב II",
    "Sochaux": "סושו",
    "Sokół Kleczew": "סוקול קלצ'ב",
    "Southampton": "סאות'המפטון",
    "Spakenburg": "ספקנבורח",
    "Sparta Nijkerk": "ספרטה נייקרק",
    "Sparta Rotterdam": "ספארטה רוטרדם",
    "Sporting Gijon": "ספורטינג חיחון",
    "Sportlust '46": "ספורטלוסט '46",
    "SpVgg Greuther Fürth": "גרויטר פירת'",
    "SSV Jeddeloh": "SSV ידלו",
    "Stade Brestois 29": "ברסט",
    "Stal Rzeszów": "סטל ז'שוב",
    "Staphorst": "סטפורסט",
    "Stevenage": "סטיבנג'",
    "Stockport County": "סטוקפורט קאונטי",
    "Stoke City": "סטוק סיטי",
    "Strasbourg": "שטרסבורג",
    "Sudtirol": "סוד טירול",
    "Sunderland": "סנדרלנד",
    "Sunderland U21": "סנדרלנד U21",
    "SV Darmstadt 98": "דארמשטדט 98",
    "SV Elversberg": "אלברסברג",
    "Swansea": "סוונזי",
    "Swindon Town": "סווינדון טאון",
    "Talayuela": "טלאיואלה",
    "Tavernes": "טוורנס",
    "TEC": "TEC",
    "Tedeón": "טדאון",
    "Telstar": "טלסטאר",
    "Tenerife": "טנריפה",
    "Thame United": "ת'יים יונייטד",
    "TOGB": "TOGB",
    "Torino": "טורינו",
    "Tottenham": "טוטנהאם",
    "Tottenham Hotspur U21": "טוטנהאם הוטספר U21",
    "Toulouse": "טולוז",
    "Tranmere": "טרנמיר",
    "Truro City": "טרורו סיטי",
    "Twente": "טוונטה",
    "Tychy 71": "טיכי 71",
    "UDI '19": "UDI '19",
    "Udinese": "אודינזה",
    "Union Berlin": "יוניון ברלין",
    "Utrecht": "אוטרכט",
    "Uxbridge": "אוקסברידג'",
    "Valencia": "ולנסיה",
    "Valladolid": "ריאל ואיאדוליד",
    "Venezia": "ונציה",
    "VfB Stuttgart": "שטוטגרט",
    "VfL Bochum": "בוכום",
    "VfL Osnabrück": "אוסנבריק",
    "VfL Wolfsburg": "וולפסבורג",
    "Vicenza Virtus": "וירטוס וויצ'נצה",
    "Villarreal": "ויאריאל",
    "Virtus Entella": "וירטוס אנטלה",
    "Vvsb": "VVSB",
    "Walsall": "וולסול",
    "Waltham Abbey": "וולת'האם אבי",
    "Watford": "ווטפורד",
    "Werder Bremen": "וורדר ברמן",
    "West Brom": "ווסט ברומיץ' אלביון",
    "West Ham": "ווסט האם",
    "Weston-super-Mare": "וסטון-סופר-מייר",
    "Widzew Łódź": "ווידזב לודג'",
    "Wieczysta Kraków": "וייצ'יסטה קרקוב",
    "Wigan": "וויגן",
    "Willem II": "וילם השני",
    "Wimborne Town": "וימבורן טאון",
    "Wingate & Finchley": "ווינגייט אנד פינצ'לי",
    "Wisla Krakow": "וויסלה קרקוב",
    "Wisla Plock": "וויסלה פלוצק",
    "Wolves": "וולבס",
    "Worksop Town": "וורקסופ טאון",
    "Wrexham": "רקסהאם",
    "Wycombe": "וויקם וונדררס",
    "Yate Town": "ייט טאון",
    "York": "יורק",
    "Zaglebie Lubin": "זגלנבייה לובין",
    "Znicz Pruszków": "זניץ' פרושקוב",
    "Zwaluwen": "זוואלואן",
    "Alvechurch": "אלווצ'רץ'",
    "Atherton Collieries": "את'רטון קוליריז",
    "Barton Town Old Boys": "ברטון טאון אולד בויז",
    "Berkhamsted": "ברקהמסטד",
    "Brackley Town": "בראקלי טאון",
    "Bradford (Park Avenue)": "ברדפורד (פארק אבניו)",
    "Bromsgrove Sporting": "ברומסגרוב ספורטינג",
    "Bury": "ברי",
    "Bury Town": "ברי טאון",
    "Buxton": "בקסטון",
    "Cambridge City": "קיימברידג' סיטי",
    "Chelmsford City": "צ'למספורד סיטי",
    "Chertsey Town": "צ'רטסי טאון",
    "Chesham United": "צ'שהאם יונייטד",
    "Chester": "צ'סטר",
    "Chorley": "צ'ורלי",
    "Coventry United": "קובנטרי יונייטד",
    "Darlington 1883": "דרלינגטון 1883",
    "Dartford": "דארטפורד",
    "Dorking Wanderers": "דורקינג וונדררס",
    "Dover": "דובר אתלטיק",
    "Dulwich Hamlet": "דולוויץ' המלט",
    "Ebbsfleet United": "אבספליט יונייטד",
    "Enfield Town": "אנפילד טאון",
    "Gloucester City": "גלוסטר סיטי",
    "Guiseley AFC": "גייזלי AFC",
    "Halesowen Town": "הילסואן טאון",
    "Hanwell Town": "האנוול טאון",
    "Hanworth Villa": "הנוורת' וילה",
    "Harborough Town": "הארבורו טאון",
    "Horsham": "הורשאם",
    "Kettering Town": "קטרינג טאון",
    "Leatherhead": "לת'רהד",
    "Leiston": "ליסטון",
    "Macclesfield": "מקלספילד",
    "Marine": "מארין",
    "Morecambe": "מורקאם",
    "Mulbarton Wanderers": "מולברטון וונדררס",
    "Oxford City": "אוקספורד סיטי",
    "Plymouth Parkway": "פלימות' פארקוויי",
    "Real Bedford": "ריאל בדפורד",
    "Redditch United": "רדיץ' יונייטד",
    "SE Dons": "SE דונס",
    "Salisbury": "סולסברי",
    "Scarborough Athletic": "סקארבורו אתלטיק",
    "Sheppey United": "שפי יונייטד",
    "Sholing": "שולינג",
    "South Shields": "סאות' שילדס",
    "Southall": "סאות'הול",
    "Spalding United": "ספולדינג יונייטד",
    "Spennymoor Town": "ספנימור טאון",
    "St Albans City": "סנט אולבנס סיטי",
    "Stafford Rangers": "סטאפורד ריינג'רס",
    "Tadley Calleva": "טאדלי קאלבה",
    "Tonbridge Angels": "טונברידג' אנג'לס",
    "Torquay": "טורקיי",
    "Trafford": "טראפורד",
    "Warrington Town": "וורינגטון טאון",
    "Weymouth": "ווימות'",
    "Worcester City": "וורצ'סטר סיטי",
    "Club Brugge KV": "קלאב ברוז'",
    "Galatasaray": "גלאטסראיי",
    "Lask Linz": "לאסק לינץ",
    "Fenerbahçe": "פנרבחצ'ה",
    "Bodo/Glimt": "בודה/גלימט",
    "FC Porto": "פורטו",
    "Slovan Bratislava": "סלובן ברטיסלבה",
    "Torreense": "טורנסה",
    "Hapoel Beer Sheva": "הפועל באר שבע",
    "Red Bull Salzburg": "רד בול זלצבורג",
    "Union St. Gilloise": "אוניון סן-ז'ילואז",
    "HNK Hajduk Split": "היידוק ספליט",
    "Universitatea Craiova": "אוניברסיטטה קראיובה",
    "CSKA Sofia": "צסק\"א סופיה",
    "Sturm Graz": "שטורם גראץ",
    "Kauno Žalgiris": "קאונו ז'לגיריס",
    "Olympiakos Piraeus": "אולימפיאקוס",
    "OFI": "OFI כרתים",
    "Besiktas": "בשיקטאש",
    "Ararat-Armenia": "אררט ארמניה",
    "Levski Sofia": "לבסקי סופיה",
    "FK Jablonec": "פ.ק. יבלונץ",
    "FC Thun": "ת'ון",
    "Sabah FA": "סבאח",
    "AEK Athens FC": "א.א.ק אתונה",
    "Celtic": "סלטיק",
    "Lillestrom": "לילסטרום",
    "Lincoln Red Imps FC": "לינקולן רד אימפס",
    "Ferencvarosi TC": "פרנצווארוש",
    "Sparta Praha": "ספרטה פראג",
    "Slavia Praha": "סלביה פראג",
    "FC Midtjylland": "מיטיולן",
    "Benfica": "בנפיקה ליסבון",
    "Trabzonspor": "טרבזונספור",
}

# keyed by "City|Country" (matches the API's country label, e.g. "England")
HE_CITIES = {
    "Accrington|England": "אקרינגטון",
    "Albacete|Spain": "אלבסטה",
    "Alkmaar|Netherlands": "אלקמאר",
    "Almería|Spain": "אלמריה",
    "Amsterdam|Netherlands": "אמסטרדם",
    "Angers|France": "אנז'ה",
    "Annecy|France": "אנסי",
    "Arezzo|Italy": "ארצו",
    "Ascoli Piceno|Italy": "אסקולי פיצ'נו",
    "Aspach|Germany": "אשפאך",
    "Assen|Netherlands": "אסן",
    "Augsburg|Germany": "אוגסבורג",
    "Auxerre|France": "אוסר",
    "Avellino|Italy": "אוולינו",
    "Azkoitia|Spain": "אסקויטייה",
    "Barcelona|Spain": "ברצלונה",
    "Barnsley|England": "בארנסלי",
    "Benevento|Italy": "בנוונטו",
    "Bergamo|Italy": "ברגמו",
    "Berkel en Rodenrijs|Netherlands": "ברקל אן רודנרייס",
    "Berlin|Germany": "ברלין",
    "Bialystok|Poland": "ביאליסטוק",
    "Bielefeld|Germany": "בילפלד",
    "Bilbao|Spain": "בילבאו",
    "Birkenhead|England": "בירקנהד",
    "Birmingham|England": "ברמינגהאם",
    "Blackburn|England": "בלקברן",
    "Blackpool|England": "בלקפול",
    "Bochum|Germany": "בוכום",
    "Bologna|Italy": "בולוניה",
    "Bolton|England": "בולטון",
    "Bolzano|Italy": "בולצאנו",
    "Boulogne-sur-Mer|France": "בולון סור מר",
    "Bournemouth|England": "בורנמות'",
    "Bradford|England": "ברדפורד",
    "Braintree, Essex|England": "בריינטרי, אסקס",
    "Braunschweig|Germany": "בראונשווייג",
    "Bremen|Germany": "ברמן",
    "Brest|France": "ברסט",
    "Brighton|England": "ברייטון",
    "Bristol|England": "בריסטול",
    "Bromley|England": "ברומלי",
    "Bunschoten|Netherlands": "בונסחוטן",
    "Burgos|Spain": "בורגוס",
    "Burnley|England": "ברנלי",
    "Burton upon Trent|England": "ברטון און טרנט",
    "Cadiz|Spain": "קאדיס",
    "Cagliari|Italy": "קליארי",
    "Calatayud|Spain": "קלטיוד",
    "Cambridge|England": "קיימברידג'",
    "Cardiff|England": "קארדיף",
    "Carrara|Italy": "קררה",
    "Castellammare di Stabia|Italy": "קסטלמארה די סטביה",
    "Castellón de la Plana|Spain": "קסטיון דה לה פלאנה",
    "Catanzaro|Italy": "קטנזארו",
    "Cesena|Italy": "צ'זנה",
    "Ceuta|Spain": "סאוטה",
    "Cheltenham|England": "צ'לטנהאם",
    "Chesterfield|England": "צ'סטרפילד",
    "Chiavari|Italy": "קיאוארי",
    "Chippenham, Wiltshire|England": "צ'יפנהאם, ווילטשייר",
    "Cleethorpes|England": "קליית'ורפס",
    "Clermont-Ferrand|France": "קלרמון-פראן",
    "Colchester|England": "קולצ'סטר",
    "Cologne|Germany": "קלן",
    "Como|Italy": "קומו",
    "Cordoba|Spain": "קורדובה",
    "Cornella de Llobregat|Spain": "קורנייה דה יוברגאט",
    "Cottbus|Germany": "קוטבוס",
    "Coventry|England": "קובנטרי",
    "Crawley|England": "קרולי",
    "Cremona|Italy": "קרמונה",
    "Crewe|England": "קרו",
    "Crowborough, East Sussex|England": "קראוובורו, איסט סאסקס",
    "Częstochowa|Poland": "צ'נסטוחובה",
    "Dagenham, Essex|England": "דגנהאם, אסקס",
    "Darmstadt|Germany": "דארמשטדט",
    "Den Haag|Netherlands": "דן האג",
    "Derby|England": "דרבי",
    "Deventer|Netherlands": "דוונטר",
    "Dijon|France": "דיז'ון",
    "Doncaster|England": "דונקסטר",
    "Dortmund|Germany": "דורטמונד",
    "Dresden|Germany": "דרזדן",
    "Dunkerque|France": "דנקרק",
    "Echt-Susteren|Netherlands": "אכט-סוסטרן",
    "Edewecht|Germany": "אדוכט",
    "Eibar|Spain": "אייבר",
    "Eindhoven|Netherlands": "איינדהובן",
    "El Prat de Llobregat|Spain": "אל פראט",
    "Elche|Spain": "אלצ'ה",
    "Elda|Spain": "אלדה",
    "Elizondo|Spain": "אליסונדו",
    "Empoli|Italy": "אמפולי",
    "Encamp|Spain": "אנקמפ",
    "Enschede|Netherlands": "אנסחדה",
    "Essen|Germany": "אסן",
    "Exeter|England": "אקסטר",
    "Exmouth, Devonshire|England": "אקסמות', דבונשייר",
    "Farnborough, Hampshire|England": "פארנבורו, המפשייר",
    "Farnham, Surrey|England": "פארנהאם, סארי",
    "Fleetwood|England": "פליטווד",
    "Florence|Italy": "פירנצה",
    "Frankfurt|Germany": "פרנקפורט",
    "Freiburg|Germany": "פרייבורג",
    "Frosinone|Italy": "פרוזינונה",
    "Fürth|Germany": "פירת'",
    "Gainsborough, Lincolnshire|England": "גיינסבורו, לינקולנשייר",
    "Gdansk|Poland": "גדנסק",
    "Gdynia|Poland": "גדיניה",
    "Gelsenkirchen|Germany": "גלזנקירכן",
    "Genoa|Italy": "ג'נובה",
    "Getafe|Spain": "חטאפה",
    "Gijón|Spain": "חיחון",
    "Gillingham|England": "ג'ילינגהאם",
    "Girona|Spain": "ג'ירונה",
    "Gliwice|Poland": "גליביצה",
    "Głogów|Poland": "גלוגוב",
    "Granada|Spain": "גרנדה",
    "Grenoble|France": "גרנובל",
    "Groesbeek|Netherlands": "חרוסביק",
    "Groningen|Netherlands": "חרונינגן",
    "Grudziądz|Poland": "גרודזיונדז",
    "Güímar|Spain": "גוימאר",
    "Guingamp|France": "גאנגאן",
    "Haarlem|Netherlands": "הארלם",
    "Hamburg|Germany": "המבורג",
    "Hannover|Germany": "הנובר",
    "Hardenberg|Netherlands": "הארדנברג",
    "Heerenveen|Netherlands": "הרנפין",
    "Heerlen|Netherlands": "הרלן",
    "Heidenheim|Germany": "היידנהיים",
    "High Wycombe|England": "היי וויקם",
    "Huddersfield|England": "האדרספילד",
    "Hull|England": "האל",
    "Ibiza|Spain": "איביזה",
    "Ipswich|England": "איפסוויץ'",
    "Isilemulino|France": "איזילמולינו",
    "Kaiserslautern|Germany": "קייזרסלאוטרן",
    "Karlsruhe|Germany": "קרלסרוהה",
    "Katowice|Poland": "קטוביצה",
    "Katwijk aan Zee|Netherlands": "קטווייק אאן זי",
    "Kiel|Germany": "קיל",
    "Kielce|Poland": "קיילצה",
    "Kleczew|Poland": "קלצ'ב",
    "Kloetinge|Netherlands": "קלוטינחה",
    "Kraków|Poland": "קרקוב",
    "La Coruña|Spain": "לה קורוניה",
    "Las Palmas|Spain": "לאס פלמאס",
    "Laval|France": "לאבאל",
    "Le Havre|France": "לה הבר",
    "Le Mans|France": "לה מאן",
    "Lebrija|Spain": "לבריחה",
    "Lecce|Italy": "לצ'ה",
    "Leczna|Poland": "לנצ'נה",
    "Leeds|England": "לידס",
    "Leeuwarden|Netherlands": "לואוארדן",
    "Leganes|Spain": "לגאנס",
    "Leicester|England": "לסטר",
    "Leipzig|Germany": "לייפציג",
    "Lens|France": "לאנס",
    "Leverkusen|Germany": "לברקוזן",
    "Lille|France": "ליל",
    "Lincoln|England": "לינקולן",
    "Liverpool|England": "ליברפול",
    "Lodz|Poland": "לודג'",
    "London|England": "לונדון",
    "Lubin|Poland": "לובין",
    "Lublin|Poland": "לובלין",
    "Luton|England": "לוטון",
    "Lyon|France": "ליון",
    "Madrid|Spain": "מדריד",
    "Magdeburg|Germany": "מגדבורג",
    "Maidstone, Kent|England": "מיידסטון, קנט",
    "Mainz|Germany": "מיינץ",
    "Malaga|Spain": "מלאגה",
    "Málaga|Spain": "מלאגה",
    "Manchester|England": "מנצ'סטר",
    "Mansfield|England": "מנספילד",
    "Mantova|Italy": "מנטובה",
    "Maracena|Spain": "מרסנה",
    "Marseille|France": "מארסיי",
    "Melilla|Spain": "מלייה",
    "Metz|France": "מץ",
    "Middlesbrough|England": "מידלסברו",
    "Milan|Italy": "מילאנו",
    "Milton Keynes|England": "מילטון קיינס",
    "Modena|Italy": "מודנה",
    "Monaco|France": "מונאקו",
    "Mönchengladbach|Germany": "מנשנגלדבך",
    "Montbéliard|France": "מונבליאר",
    "Montpellier|France": "מונפלייה",
    "Monza|Italy": "מונצה",
    "Munich|Germany": "מינכן",
    "Nancy|France": "נאנסי",
    "Nantes|France": "נאנט",
    "Naples|Italy": "נאפולי",
    "Navarrete|Spain": "נווארטה",
    "Newcastle|England": "ניוקאסל",
    "Newport|England": "ניופורט",
    "Nice|France": "ניס",
    "Niepołomice|Poland": "ניפולומיצה",
    "Nijkerk|Netherlands": "ניקרק",
    "Nijmegen|Netherlands": "ניימכן",
    "Noja|Spain": "נוחה",
    "Noordwijk|Netherlands": "נורדוויק",
    "Northampton|England": "נורת'המפטון",
    "Norwich|England": "נוריץ'",
    "Nottingham|England": "נוטינגהאם",
    "Nuremberg|Germany": "נירנברג",
    "Oldham|England": "אולדהאם",
    "Opole|Poland": "אופולה",
    "Osnabrück|Germany": "אוסנבריק",
    "Oviedo|Spain": "אוביידו",
    "Oxford|England": "אוקספורד",
    "Paderborn|Germany": "פדרבורן",
    "Padova|Italy": "פדובה",
    "Palermo|Italy": "פלרמו",
    "Palma de Mallorca|Spain": "פלמה דה מיורקה",
    "Pamplona|Spain": "פמפלונה",
    "Paris - Saint-Ouen|France": "פריז - סן-אואן",
    "Paris|France": "פריז",
    "Parma|Italy": "פארמה",
    "Pau|France": "פו",
    "Peterborough|England": "פיטרבורו",
    "Pisa|Italy": "פיזה",
    "Płock|Poland": "פלוצק",
    "Plymouth|England": "פלימות'",
    "Portsmouth|England": "פורטסמות'",
    "Poznań|Poland": "פוזנן",
    "Preston|England": "פרסטון",
    "Pruszków|Poland": "פרושקוב",
    "Radom|Poland": "רדום",
    "Reading|England": "רדינג",
    "Reggio Emilia|Italy": "רג'ו אמיליה",
    "Reims|France": "ראנס",
    "Rennes|France": "רן",
    "Rijssen|Netherlands": "רייסן",
    "Rochdale|England": "רוצ'דייל",
    "Rodez|France": "רודז",
    "Rome|Italy": "רומא",
    "Rotherham|England": "רות'רהאם",
    "Rotterdam|Netherlands": "רוטרדם",
    "Sabadell|Spain": "סבאדל",
    "Saint-Ètienne|France": "סנט אטיין",
    "Salford|England": "סאלפורד",
    "San Sebastian|Spain": "סן סבסטיאן",
    "Santa Cruz de Tenerife|Spain": "סנטה קרוס דה טנריפה",
    "Santander|Spain": "סנטנדר",
    "Sevilla|Spain": "סביליה",
    "Sheffield|England": "שפילד",
    "Shrewsbury|England": "שרוסברי",
    "Sinsheim|Germany": "זינסהיים",
    "Sittard|Netherlands": "סיטארד",
    "Sosnowiec|Poland": "סוסנוביץ'",
    "Southampton|England": "סאות'המפטון",
    "Spakenburg|Netherlands": "ספקנבורח",
    "Spiesen-Elversberg|Germany": "שפיזן-אלברסברג",
    "Środa Wielkopolska|Poland": "שרודה וילקופולסקה",
    "Staphorst|Netherlands": "סטפורסט",
    "Stevenage|England": "סטיבנג'",
    "Stockport|England": "סטוקפורט",
    "Stoke on Trent|England": "סטוק און טרנט",
    "Strasbourg|France": "שטרסבורג",
    "Stuttgart|Germany": "שטוטגרט",
    "Sunderland|England": "סנדרלנד",
    "Swansea|England": "סוונזי",
    "Świdnik|Poland": "שווידניק",
    "Swindon|England": "סווינדון",
    "Szczecin|Poland": "שצ'צ'ין",
    "Tarnobrzeg|Poland": "טרנוברז'ג",
    "Tilburg|Netherlands": "טילבורח",
    "Toulouse|France": "טולוז",
    "Troyes|France": "טרואה",
    "Truro, Cornwall|England": "טרורו, קורנוול",
    "Turin|Italy": "טורינו",
    "Tychy|Poland": "טיכי",
    "Udine|Italy": "אודינה",
    "Utrecht|Netherlands": "אוטרכט",
    "Valencia|Spain": "ולנסיה",
    "Valladolid|Spain": "ואיאדוליד",
    "Veenendaal|Netherlands": "פינדאל",
    "Velsen-Zuid|Netherlands": "ולזן-זוד",
    "Venice|Italy": "ונציה",
    "Verona|Italy": "ורונה",
    "Vicenza|Italy": "וויצ'נצה",
    "Vigo|Spain": "ויגו",
    "Villarreal|Spain": "ויאריאל",
    "Vitoria-Gasteiz|Spain": "ויטוריה-גסטייז",
    "Vlaardingen|Netherlands": "פלארדינחן",
    "Volendam|Netherlands": "פולנדם",
    "Walsall|England": "וולסול",
    "Warsaw|Poland": "ורשה",
    "Watford|England": "ווטפורד",
    "West Bromwich|England": "ווסט ברומוויץ'",
    "Wigan|England": "וויגן",
    "Wimbledon|England": "ווימבלדון",
    "Wimborne Minster, Dorset|England": "וימבורן מינסטר, דורסט",
    "Wirral|England": "ווירל",
    "Woerden|Netherlands": "וורדן",
    "Wolfsburg|Germany": "וולפסבורג",
    "Wolverhampton|England": "וולברהמפטון",
    "Worksop, Nottinghamshire|England": "וורקסופ, נוטינגהאמשייר",
    "Wrexham|England": "רקסהאם",
    "Wrocław|Poland": "ורוצלב",
    "York|England": "יורק",
    "Zabrze|Poland": "זבז'ה",
    "Zwolle|Netherlands": "זוואלה",
    "Barton-upon-Humber, Lincolnshire|England": "ברטון-אפון-האמבר, לינקולנשייר",
    "Brackley, Northamptonshire|England": "בראקלי, נורת'המפטונשייר",
    "Bury St Edmunds, Suffolk|England": "ברי סנט אדמונדס, סאפוק",
    "Bury, Lancashire|England": "ברי, לנקשייר",
    "Buxton, Derbyshire|England": "בקסטון, דרבישייר",
    "Chesham, Buckinghamshire|England": "צ'שהאם, בקינגהאמשייר",
    "Crosby, Merseyside|England": "קרוסבי, מרסיסייד",
    "Dorking, Surrey|England": "דורקינג, סארי",
    "Flixton, Greater Manchester|England": "פליקסטון, גרייטר מנצ'סטר",
    "Guiseley, West Yorkshire|England": "גייזלי, וסט יורקשייר",
    "Kettering, Northamptonshire|England": "קטרינג, נורת'המפטונשייר",
    "Leatherhead, Surrey|England": "לת'רהד, סארי",
    "Leiston, Suffolk|England": "ליסטון, סאפוק",
    "Lorient|France": "לוריאן",
    "Macclesfield, Cheshire|England": "מקלספילד, צ'שייר",
    "Market Harborough, Leicestershire|England": "מארקט הארבורו, לסטרשייר",
    "Morecambe, Lancashire|England": "מורקאם, לנקשייר",
    "Mulbarton, Norfolk|England": "מולברטון, נורפוק",
    "Northfleet, Kent|England": "נורת'פליט, קנט",
    "Oxford, Oxfordshire|England": "אוקספורד, אוקספורדשייר",
    "Plymouth, Devon|England": "פלימות', דבון",
    "Redditch, Worcestershire|England": "רדיץ', וורצ'סטרשייר",
    "Salisbury, Wiltshire|England": "סולסברי, ווילטשייר",
    "Sawston, Cambridgeshire|England": "סוסטון, קיימברידג'שייר",
    "Sheerness|England": "שירנס",
    "Spennymoor, County Durham|England": "ספנימור, קאונטי דרהאם",
    "Stafford, Staffordshire|England": "סטאפורד, סטאפורדשייר",
    "Tadley, Hampshire|England": "טאדלי, המפשייר",
    "Tonbridge, Kent|England": "טונברידג', קנט",
    "Weymouth, Dorset|England": "ווימות', דורסט",
    "Ourense|Spain": "אורנסה",
    "Soria|Spain": "סוריה",
    "Alcázar de San Juan|Spain": "אלקסר דה סן חואן",
    "Tavernes de la Valldigna|Spain": "טוורנס דה לה ואיידיגנה",
    "San Pedro del Pinatar|Spain": "סן פדרו דל פינטאר",
    "Talayuela|Spain": "טלאיואלה",
    "Ribadesella|Spain": "ריבדסיה",
    "Brugge|Belgium": "ברוז'",
    "Istanbul|Turkey": "איסטנבול",
    "Linz|Austria": "לינץ",
    "Stavanger|Norway": "סטוונגר",
    "Bratislava|Slovakia": "ברטיסלבה",
    "Torres Vedras|Portugal": "טורס ודרס",
    "Beer Sheva|Israel": "באר שבע",
    "Salzburg|Austria": "זלצבורג",
    "Brussels|Belgium": "בריסל",
    "Craiova|Romania": "קראיובה",
    "Sofia|Bulgaria": "סופיה",
    "Graz|Austria": "גראץ",
    "Heraklion|Greece": "הרקליון",
    "Yerevan|Armenia": "ירוואן",
    "Jablonec nad Nisou|Czechia": "יבלונץ נד ניסו",
    "Masazir|Azerbaijan": "מסזיר",
    "Athens|Greece": "אתונה",
    "Villeneuve-d'Ascq|France": "וילנב-ד'אסק",
    "Glasgow|Scotland": "גלזגו",
    "Lillestrøm|Norway": "לילסטרום",
    "Gibraltar|Gibraltar": "גיברלטר",
    "Budapest|Hungary": "בודפשט",
    "Bodø|Norway": "בודה",
    "Prague|Czechia": "פראג",
    "Lisbon|Portugal": "ליסבון",
    "Trabzon|Turkey": "טרבזון",
}

_CONS = {
    "b": "ב", "c": "ק", "d": "ד", "f": "פ", "g": "ג", "h": "ה", "j": "ג'", "k": "ק",
    "l": "ל", "m": "מ", "n": "נ", "p": "פ", "q": "ק", "r": "ר", "s": "ס", "t": "ט",
    "v": "ו", "w": "ו", "x": "קס", "z": "ז",
}
_DIGRAPHS = [
    ("tch", "טש"), ("sch", "ש"), ("sh", "ש"), ("ch", "צ'"), ("th", "ת'"),
    ("ph", "פ"), ("ck", "ק"), ("qu", "קוו"), ("wh", "וו"), ("gh", ""),
]
_VOWELS = [
    ("ee", "אי"), ("ea", "אי"), ("oo", "u"), ("ou", "אאו"), ("ow", "אאו"),
    ("ay", "אי"), ("ai", "אי"), ("oy", "וי"), ("ey", "אי"), ("ie", "אי"),
    ("a", "א"), ("e", ""), ("i", "י"), ("o", "ו"), ("u", "יו"), ("y", "י"),
    ("ø", "ו"), ("å", "ו"), ("æ", "א"),
]


def transliterate(name):
    """Best-effort phonetic Hebrew transliteration for a name not in the dictionaries above."""
    out, i, s = [], 0, name.lower()
    while i < len(s):
        ch = s[i]
        if not ch.isalpha():
            out.append(ch)
            i += 1
            continue
        matched = False
        for pat, rep in _DIGRAPHS + _VOWELS:
            if s.startswith(pat, i):
                out.append(rep)
                i += len(pat)
                matched = True
                break
        if matched:
            continue
        out.append(_CONS.get(ch, ch))
        i += 1
    result = "".join(out).strip()
    # keep the original capitalization/spacing cues for acronyms (all-caps tokens) as-is
    words_he, words_en = result.split(), name.split()
    if len(words_he) == len(words_en):
        for idx, w in enumerate(words_en):
            if w.isupper() and len(w) <= 5:
                words_he[idx] = w
        result = " ".join(words_he)
    return result or name


def he_team(name):
    return HE_TEAMS.get(name) or transliterate(name)


def he_city(city, country):
    if not city:
        return city
    return HE_CITIES.get(f"{city}|{country}") or transliterate(city)


def he_comp(label):
    return HE_COMPETITIONS.get(label) or label
